"""Bosnian name pools for the synthetic seed (all names are invented/synthetic)."""

HOTEL_GROUPS: list[str] = [
    "Hotel Stari Grad",
    "Hotel Panorama",
    "Hotel Aria",
    "Hotel Vrelo Bosne",
    "Hotel Zlatna Dolina",
]

HOTEL_OBJECTS: list[str] = [
    "domaćinstvo",
    "restoran",
    "wellness centar",
    "kongresni centar",
    "recepcija i lobi",
]

RESTORAN_NAMES: list[str] = [
    "Restoran Šadrvan",
    "Restoran Behar",
    "Restoran Kibe",
    "Restoran Lovac",
    "Restoran Stara Kuća",
    "Restoran Merak",
    "Restoran Vidikovac",
    "Restoran Bosanska Avlija",
    "Restoran Čaršija",
    "Restoran Zlatna Ribica",
    "Restoran Sofra",
    "Restoran Bašta",
    "Restoran Sedef",
    "Restoran Galija",
    "Restoran Dva Ribara",
    "Restoran Kod Hane",
    "Restoran Mlinica",
    "Restoran Panorama",
    "Restoran Jezero",
    "Restoran Brajlović",
]

KAFIC_NAMES: list[str] = [
    "Caffe Ministarstvo",
    "Caffe Tito",
    "Kafana Kod Bake",
    "Caffe Slatko Ćoše",
    "Caffe Galerija",
    "Caffe Promenada",
    "Caffe Meeting Point",
    "Kafe Dibek",
    "Caffe Opera",
    "Caffe Baščaršija",
    "Caffe Park",
    "Caffe Centar",
    "Kafana Stara Vremena",
    "Caffe Mostić",
    "Caffe Atelje",
    "Caffe Zvono",
    "Caffe Lungo",
    "Caffe Vrelo",
]

KLINIKA_NAMES: list[str] = [
    "Poliklinika Sunce",
    "Stomatološka ordinacija Dent",
    "Poliklinika Vitalis",
    "Ordinacija Dr. Hadžić",
    "Poliklinika Medicus",
    "Privatna klinika Eskulap",
    "Stomatološka klinika Smile",
    "Poliklinika Salus",
    "Dermatološka ordinacija Derma",
    "Oftalmološka klinika Oko",
    "Fizioterapija Reha Centar",
    "Ginekološka ordinacija Vita",
    "Pedijatrijska ordinacija Leptirić",
]

SKOLA_NAMES: list[str] = [
    "OŠ Safvet-beg Bašagić",
    "OŠ Skender Kulenović",
    "OŠ Mula Mustafa Bašeskija",
    "Gimnazija Obala",
    "OŠ Aleksa Šantić",
    "Srednja ekonomska škola",
    "OŠ Hasan Kikić",
    "Srednja medicinska škola",
    "OŠ Isak Samokovlija",
    "Gimnazija Meša Selimović",
    "OŠ Kovačići",
    "Srednja građevinska škola",
    "OŠ Vladislav Skarić",
    "Muzička škola Sarajevo",
    "OŠ Grbavica I",
    "Srednja ugostiteljska škola",
]

FIRST_NAMES: list[str] = [
    "Amir",
    "Selma",
    "Emir",
    "Lejla",
    "Adnan",
    "Amina",
    "Tarik",
    "Merima",
    "Haris",
    "Aida",
    "Damir",
    "Jasmina",
    "Kenan",
    "Elma",
    "Nedim",
    "Azra",
    "Samir",
    "Alma",
    "Mirza",
    "Emina",
    "Faruk",
    "Sanela",
    "Vedad",
    "Maja",
    "Goran",
    "Ivana",
    "Zlatan",
    "Dženita",
]

LAST_NAMES: list[str] = [
    "Hodžić",
    "Begović",
    "Čengić",
    "Imamović",
    "Softić",
    "Hadžiahmetović",
    "Zukić",
    "Mehmedović",
    "Karahasanović",
    "Delić",
    "Kovačević",
    "Smajlović",
    "Bašić",
    "Salihović",
    "Memić",
    "Husić",
    "Šehić",
    "Ahmetović",
    "Pjanić",
    "Đulić",
]

STREETS: list[str] = [
    "Ferhadija",
    "Maršala Tita",
    "Zmaja od Bosne",
    "Obala Kulina bana",
    "Mula Mustafe Bašeskije",
    "Branilaca Sarajeva",
    "Alipašina",
    "Koševo",
    "Titova",
    "Vilsonovo šetalište",
    "Džemala Bijedića",
    "Hamdije Kreševljakovića",
]

SALES_REP_NAMES: list[str] = [
    "Adis Mujanović",
    "Lamija Šabanović",
    "Eldar Hadžimuratović",
    "Naida Kapetanović",
]

# Article names per category — ~120 total, realistic hygiene-distribution items.
ARTICLE_NAMES: dict[str, list[str]] = {
    "papir": [
        "Toaletni papir 3-sl 8/1",
        "Toaletni papir jumbo 12/1",
        "Toaletni papir 2-sl 10/1",
        "Papirni ubrusi Z-fold 20/1",
        "Papirni ubrusi V-fold 20/1",
        "Papirna rola 2-sl 6/1",
        "Papirna rola industrijska 2/1",
        "Salvete 33x33 bijele 100/1",
        "Salvete 33x33 u boji 100/1",
        "Salvete 24x24 bijele 200/1",
        "Salvete koktel 24x24 100/1",
        "Podmetači papirni 100/1",
        "Papirne kese 26x35 50/1",
        "Papir za pečenje 38cm",
        "Ubrusi u rolni Maxi 2/1",
        "Ubrusi u rolni Mini 12/1",
        "Toaletni papir u listićima 250/1",
        "Medicinska rola 50cm",
        "Medicinska rola 60cm",
        "Papirni stolnjak 1x100m",
        "Higijenski ulošci za WC dasku 100/1",
        "Papirne maramice 10x10",
        "Kuhinjski ubrusi 2/1",
        "Papirna galanterija set",
    ],
    "hemija": [
        "Sredstvo za pranje podova 5L",
        "Sredstvo za pranje podova 1L",
        "Dezinficijens za ruke 1L",
        "Dezinficijens za ruke 5L",
        "Dezinficijens za površine 1L",
        "Dezinficijens za površine 5L",
        "Sredstvo za staklo 750ml",
        "Sredstvo za staklo 5L",
        "Sredstvo za sanitarije 750ml",
        "Sredstvo za sanitarije 5L",
        "Deterdžent za suđe 1L",
        "Deterdžent za suđe 5L",
        "Deterdžent za veš 8kg",
        "Omekšivač za veš 5L",
        "Sredstvo za kamenac 1L",
        "Sredstvo za rernu 750ml",
        "Sredstvo za inox 500ml",
        "Osvježivač prostora 300ml",
        "Sredstvo za tepihe 5L",
        "Sredstvo za drvene površine 1L",
        "Hlor tablete 1kg",
        "Tečni hlor 5L",
        "Abrazivno sredstvo 500g",
        "Sapunica za mašinsko pranje 10L",
        "Sredstvo za odmašćivanje 5L",
        "Univerzalno sredstvo za čišćenje 1L",
    ],
    "dispenzeri": [
        "Dispenzer za tečni sapun 1L",
        "Dispenzer za pjenušavi sapun 800ml",
        "Dispenzer za dezinficijens senzorski",
        "Dispenzer za papirne ubruse Z-fold",
        "Dispenzer za toaletni papir jumbo",
        "Dispenzer za toaletni papir u listićima",
        "Dispenzer za salvete stolni",
        "Dispenzer za WC daske uloške",
        "Osvježivač prostora automatski",
        "Dispenzer za rukavice zidni",
        "Stalak za dezinfekciju samostojeći",
        "Dispenzer za papirnu rolu zidni",
    ],
    "rukavice": [
        "Rukavice nitrilne S 100/1",
        "Rukavice nitrilne M 100/1",
        "Rukavice nitrilne L 100/1",
        "Rukavice nitrilne XL 100/1",
        "Rukavice lateks M 100/1",
        "Rukavice lateks L 100/1",
        "Rukavice vinil M 100/1",
        "Rukavice PE jednokratne 100/1",
        "Rukavice za domaćinstvo gumene",
        "Rukavice radne zaštitne",
    ],
    "kozmetika": [
        "Tečni sapun 5L",
        "Tečni sapun 1L pumpica",
        "Pjenušavi sapun punjenje 800ml",
        "Šampon za kosu 1L",
        "Šampon i gel 2u1 5L",
        "Gel za tuširanje 1L",
        "Krema za ruke 100ml",
        "Hotelski sapun 15g 100/1",
        "Hotelski šampon 30ml 100/1",
        "Hotelska kapa za tuširanje 100/1",
        "Hotelski set četkica i pasta 100/1",
        "Losion za tijelo 30ml 100/1",
        "Vlažne maramice 72/1",
        "Vlažne maramice antibakterijske 80/1",
        "Pasta za ruke abrazivna 500ml",
        "Krema za njegu lica 50ml",
    ],
    "tekstil": [
        "Peškir frotir 50x100 bijeli",
        "Peškir frotir 70x140 bijeli",
        "Peškir frotir 30x50 bijeli",
        "Posteljina set 140x200 bijela",
        "Plahta 160x200 bijela",
        "Jastučnica 50x70 bijela",
        "Stolnjak damast 140x140",
        "Stolnjak damast 140x220",
        "Kuhinjska krpa pamučna 3/1",
        "Krpa od mikrofibre 5/1",
        "Bademantil frotir M",
        "Bademantil frotir L",
    ],
    "oprema": [
        "Kolica za čišćenje dvodijelna",
        "Kolica za čišćenje profesionalna",
        "Mop set komplet",
        "Mop uložak pamučni",
        "Mop uložak mikrofibra",
        "Držač mopa 40cm",
        "Teleskopska drška 140cm",
        "Kanta za mop 25L sa cjedilom",
        "Kanta za otpatke 50L pedala",
        "Kanta za otpatke 25L pedala",
        "Korpa za otpatke 12L",
        "Metla sa drškom",
        "Đubrovnik sa drškom",
        "Brisač za staklo 35cm",
        "Brisač za pod 55cm",
        "Spužva abrazivna 10/1",
        "Krpa za pod 60x70",
        "Znak upozorenja mokri pod",
        "Četka WC sa posudom",
        "Usisivač profesionalni 1400W",
    ],
}
